### ISSUE TITLE
activating plugin trigger sbt with sbt >= 1.0.1

### ISSUE THREAD

**Issue by yanns** [sbt/sbt-buildinfo#106]
Only by activating the plugin (`enablePlugins(BuildInfoPlugin)`), the triggered sbt task (like `~test`) is triggered every few seconds even if there are no changes.

I cannot reproduce this behavior with sbt 1.0.0, only with the [1.0.1 version](https://github.com/sbt/sbt/releases/tag/v1.0.1).

**Comment by bmjsmith** [comment]
This change looks related at least to the untrained eye.

https://github.com/sbt/sbt/pull/3439

**Comment by yanns** [comment]
same problem with [sbt 1.0.2](https://github.com/sbt/sbt/releases/tag/v1.0.2)

**Comment by yanns** [comment]
Anyone has found a workaround for this?
This is completely killing the auto-triggering sbt feature.  😰

**Comment by jleider** [comment]
A temporary workaround is to just ignore the file from `Compile` by adding the following to your project settings `excludeFilter in Compile := "BuildInfo.scala"`

If you are relying on up to date values during development this may cause issues?

**Comment by yanns** [comment]
The workaround is working, thx!!

**Comment by sarahgerweck** [comment]
A better workaround is, unless you rely on it, to set `sourcesInBase := false` in your projects. This disables the new "watch everything in every directory by default" "feature" that was added in SBT 1.0.1 and restores the earlier behavior. The real issue here is a bad default setting and an arguably bad implementation of an attempt to more accurately support that setting's default.

**Comment by eed3si9n** [comment]
It was definitely a bug, not a feature. @dwijnand fixed the watch-everything bug in sbt 1.0.3 - https://github.com/sbt/sbt/pull/3634
Could anyone who had issues try 1.0.3 and see if the situation improves, please? Thanks for the patience.

**Comment by sarahgerweck** [comment]
@eed3si9n I didn't realize that SBT 1.0.3 had been released: the downloads page still shows 1.0.2. It seems to fix the issue for me. Thanks!

**Comment by dwijnand** [comment]
Fixed with https://github.com/sbt/sbt/pull/3634, which shipped in sbt 1.0.3.

**Comment by yanns** [comment]
I confirm it's fixed in sbt 1.0.3.
Thanks to all involved!! ❤️
