### ISSUE TITLE
Add diffing to scripted failures

### ISSUE THREAD

**Issue by dwijnand** [sbt/sbt-buildinfo#118]
When any scripted test fails for contents difference it would be nice to have a diff result returned.

See https://github.com/sbt/contraband/commit/b40e5309e796503db7bf31019415733f12d097be and https://github.com/sbt/contraband/pull/42 for some prior art.

**Comment by eed3si9n** [comment]
sbt already contains Dotty's DiffUtil in `private[inc]` - https://github.com/sbt/zinc/blob/v1.1.1/internal/zinc-core/src/main/scala/sbt/internal/inc/APIDiff.scala
Maybe it could be made public in somewhere?

**Comment by dwijnand** [comment]
in a standalone library, sure.
