### ISSUE TITLE
BuildInfoBuildNumber is incremented on 'sbt run'

### ISSUE THREAD

**Issue by robotslave** [sbt/sbt-buildinfo#13]
...and I doubt that's the behavior users are expecting.

It looks like you might need to scope your dependency <a href="https://github.com/sbt/sbt-buildinfo/blob/master/src/main/scala/sbtbuildinfo/Plugin.scala#L152">here</a>.

I would also argue that buildNumberTask should be public, as some users might want to use it to set buildinfoBuildnumber themselves, and use buildNumberTask to put buildinfo.properties somewhere other than in the project root.

**Comment by matanster** [comment]
Is there a regression in 0.3.2 in this?
