### ISSUE TITLE
Can I set an environment variable? Time zone: TZ=UTC

### ISSUE THREAD

**Issue by kajmagnus** [sbt/sbt-buildinfo#132]
This would add the Git commit date to the build info:

    BuildInfoKey.action("gitLastCommitDateUtc") {
      "TZ=UTC git show --quiet --date='format-local:%Y-%m-%d %H:%M:%SZ' --format=\"%cd\"".!!.trim
    }),

But results in:  `java.io.IOException: Cannot run program "TZ=UTC"` — any way to set an env var and the time zone?

Looking at the `action` fn signature: `def action[A](name : scala.Predef.String)` maybe there isn't, at this time?

Background: I want somewhat reproducible builds: the last commit date, in the same time zone, for everyone. (Including the actual build time, results in the compiled build info file changing all the time, making Play Framework reload & restart & take forever, whenever anything changes.)

**Comment by charles-dyfis-net** [comment]
`env TZ=UTC ...`

**Comment by exoego** [comment]
You may find a technique describe in https://stackoverflow.com/a/42639176/9239686 useful.
You need to create a `Process` with custom environment variable,

**Comment by kajmagnus** [comment]
@charles-dyfis-net  and @exoego do you know if these two different approaches works with Windows? (Or only Linux / Mac?  I don't have Windows.)

Thanks anyway; didn't have time to try this out until now.

**Comment by exoego** [comment]
`Process` should work on Windows too.

**Comment by kajmagnus** [comment]
@exoego ok, thanks :-)  Now I got this working with Process. In `build.sbt`:

```
    // The last commit date, UTC.
    // Trying "TZ=UTC git show ..." results in java.io.IOException: Cannot run program "TZ=UTC",
    // so need to use the help program 'env'. But won't work on Windows  use Process instead.
    BuildInfoKey.action("gitLastCommitDateUtc") {
      // Linux only:
      //"env TZ=UTC git show --quiet --date='format-local:%Y-%m-%d %H:%M:%SZ' --format=\"%cd\"".!!.trim
      // Reportedly works on Windows:
      scala.sys.process.Process(
        "git show --quiet --date=format-local:%Y-%m-%dT%H:%M:%SZ --format=\"%cd\"".split(" "),
        None, "TZ" -> "UTC").!!.trim
    }),
```
