### ISSUE TITLE
Build info in HTML format?

### ISSUE THREAD

**Issue by swiesner-dlr** [sbt/sbt-buildinfo#136]
I'd like to generate a simple HTML report of the build info with an SBT task. I'd like to run this task during the CI build and publish the result as report; the idea is to have a short overview about the latest build, in particular show the latest version.

I know that the plugin doesn't support this currently, but would it be easy to add this feature?

**Comment by eed3si9n** [comment]
Not sure how easy but see https://github.com/sbt/sbt-buildinfo/pull/98 for custom renderer.

**Comment by swiesner-dlr** [comment]
@eed3si9n Thanks. This only lets me replace the current renderer, however, but I'd like to render to a case object as well as to an HTML file.  I can't just delegate to the Scala render either, because `ScalaCaseObjectRenderer` is package private.  Perhaps you could make it public?  Or is there another way to obtain an instance of that renderer?
