### ISSUE TITLE
How do I import the generated BuildInfo

### ISSUE THREAD

**Issue by avnerbarr** [sbt/sbt-buildinfo#137]
I added all the necessary parts to the sbt and see that the code is generated under

target/scala-2.11/src_managed/main/sbt-buildinfo/BuildInfo

but I don't understand how I can import that class 

```
package buildinfo

import scala.Predef._

/** This object was generated by sbt-buildinfo. */
case object BuildInfo {
  /** The value is "commons". */
  val name: String = "commons"
  /** The value is "0.5.13". */
  val version: String = "0.5.13"
  /** The value is "2.11.8". */
  val scalaVersion: String = "2.11.8"
  /** The value is "0.13.8". */
  val sbtVersion: String = "0.13.8"
  override val toString: String = {
    "name: %s, version: %s, scalaVersion: %s, sbtVersion: %s" format (
      name, version, scalaVersion, sbtVersion
    )
  }
}


```

**Comment by nunomrc** [comment]
@avnerbarr Having the same problem here. Any news?

**Comment by nunomrc** [comment]
Actually, this was not an issue, I IntelliJ was just able to see it and I could reference the new object in my existing code, where I could simply do something like:
```
import buildinfo.BuildInfo
...
println(BuildInfo.version)
```

**Comment by markosski** [comment]
@avnerbarr do you mean you had to add `sbt-buildinfo` to build.sbt (not just plugins.sbt)?

**Comment by eed3si9n** [comment]
It doesn't look like this there's a bug on sbt-buildinfo, so I am closing this.
