### ISSUE TITLE
Parallel Jenkins stages running tests on different projects cause race in sbt-buildinfo for common dependencies

### ISSUE THREAD

**Issue by dpennell** [sbt/sbt-buildinfo#139]
## Context
sbt version: 1.2.1
sbt-buildinfo version: 0.8.0

We have an sbt multi-project build file with the bt-buildinfo plugin enabled on almost all projects

Our Jenkins pipeline:

- Stage: `sbt compile, test`
-   Parallel Stages
    -  `sbt projectA/test`
    -  `sbt projectB/test`
    -  total of 17 parallel stages, each running tests on an independent leaf project

## Problem

We see random failures that manifest in many different forms that appear to have a root of missing BuildInfo class files.

## Preliminary diagnosis

Based on the minimized buildinfo code that @dwijnand posted in https://github.com/sbt/sbt/issues/3501, it appears that each of our parallel sbt <project>/test stages is causing build-info to generate temporary files in each project's cache directory. I propose to change sbt-buildinfo to use temporary file semantics (e.g. IO.withTemporaryFile). I can submit a PR if this is acceptable.

**Comment by eed3si9n** [comment]
Are you running multiple sessions of sbt based on a single disk state? If so that's not a use case sbt support in general. Each build stage should be given different working directory or Docker image or whatever as isolation.

**Comment by dpennell** [comment]
We were, but realized this was a bad idea.
