### ISSUE TITLE
Bad address error when running in play 2.7.0

### ISSUE THREAD

**Issue by kolapkardhaval** [sbt/sbt-buildinfo#144]
```
[error] java.io.IOException: Bad address
[error] 	at sun.nio.ch.FileDispatcherImpl.pwrite0(Native Method)
[error] 	at sun.nio.ch.FileDispatcherImpl.pwrite(FileDispatcherImpl.java:66)
[error] 	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:89)
[error] 	at sun.nio.ch.IOUtil.write(IOUtil.java:51)
[error] 	at sun.nio.ch.FileChannelImpl.writeInternal(FileChannelImpl.java:778)
[error] 	at sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:764)
[error] 	at sun.nio.ch.FileChannelImpl.transferFromFileChannel(FileChannelImpl.java:636)
[error] 	at sun.nio.ch.FileChannelImpl.transferFrom(FileChannelImpl.java:708)
[error] 	at sbt.io.IO$.loop$1(IO.scala:835)
[error] 	at sbt.io.IO$.$anonfun$copyFile$4(IO.scala:838)
[error] 	at sbt.io.IO$.$anonfun$copyFile$4$adapted(IO.scala:829)
[error] 	at sbt.io.Using.apply(Using.scala:22)
[error] 	at sbt.io.IO$.$anonfun$copyFile$3(IO.scala:829)
[error] 	at sbt.io.IO$.$anonfun$copyFile$3$adapted(IO.scala:828)
[error] 	at sbt.io.Using.apply(Using.scala:22)
[error] 	at sbt.io.IO$.copyFile(IO.scala:828)
[error] 	at sbtbuildinfo.BuildInfo$BuildInfoTask.$anonfun$cachedCopyFile$1(BuildInfo.scala:100)
[error] 	at sbtbuildinfo.BuildInfo$BuildInfoTask.$anonfun$cachedCopyFile$1$adapted(BuildInfo.scala:98)
[error] 	at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:149)
[error] 	at sbtbuildinfo.BuildInfo$BuildInfoTask.file(BuildInfo.scala:93)
[error] 	at sbtbuildinfo.BuildInfo$.apply(BuildInfo.scala:11)
[error] 	at sbtbuildinfo.BuildInfoPlugin$.$anonfun$buildInfoScopedSettings$1(BuildInfoPlugin.scala:68)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:278)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
```

**Comment by kolapkardhaval** [comment]
Also getting this error sometimes:
[error] (Compile / buildInfo) Could not copy '/Users/xyz/Documents/workspace/app/target/streams/compile/buildInfo/$global/streams/sbt-buildinfo/BuildInfo.scala' to '/Users/xyz/Documents/workspace/app/target/scala-2.12/src_managed/main/sbt-buildinfo/BuildInfo.scala' (1053/1053 bytes copied)
[error] java.lang.RuntimeException: Could not create directory /var/folders/4s/ccfp42j96qv43nl6fjlz7jzhl5jjtr/T/sbt_94b7dcac
[error]  at scala.sys.package$.error(package.scala:26)
[error]  at sbt.io.IO$.createDirectory(IO.scala:326)
[error]  at sbt.Defaults$.$anonfun$globalSbtCore$17(Defaults.scala:256)
[error]  at sbt.internal.Index$.$anonfun$triggers$5(EvaluateConfigurations.scala:387)
[error]  at sbt.Execute.runKeep(Execute.scala:92)
[error]  at sbt.EvaluateTask$.liftedTree1$1(EvaluateTask.scala:420)
[error]  at sbt.EvaluateTask$.run$1(EvaluateTask.scala:419)
[error]  at sbt.EvaluateTask$.runTask(EvaluateTask.scala:438)
[error]  at sbt.EvaluateTask$.$anonfun$apply$3(EvaluateTask.scala:313)
[error]  at scala.Option$WithFilter.map(Option.scala:146)
[error]  at sbt.EvaluateTask$.$anonfun$apply$1(EvaluateTask.scala:312)
[error]  at sbt.EvaluateTask$.withStreams(EvaluateTask.scala:355)
[error]  at sbt.EvaluateTask$.apply(EvaluateTask.scala:311)
[error]  at sbt.Extracted.runTask(Extracted.scala:61)
[error]  at sbtbuildinfo.BuildInfo$.entry$1(BuildInfo.scala:37)
[error]  at sbtbuildinfo.BuildInfo$.$anonfun$results$4(BuildInfo.scala:45)
[error]  at scala.collection.immutable.List.flatMap(List.scala:334)
[error]  at sbtbuildinfo.BuildInfo$.results(BuildInfo.scala:45)
[error]  at sbtbuildinfo.BuildInfo$BuildInfoTask.makeFile(BuildInfo.scala:105)
[error]  at sbtbuildinfo.BuildInfo$BuildInfoTask.file(BuildInfo.scala:92)
[error]  at sbtbuildinfo.BuildInfo$.apply(BuildInfo.scala:11)
[error]  at sbtbuildinfo.BuildInfoPlugin$.$anonfun$buildInfoScopedSettings$1(BuildInfoPlugin.scala:68)
[error]  at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]  at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error]  at sbt.std.Transform$$anon$4.work(System.scala:67)
[error]  at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error]  at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]  at sbt.Execute.work(Execute.scala:278)
[error]  at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error]  at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]  at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]  at java.lang.Thread.run(Thread.java:748)
[error] (Compile / buildInfo) Could not create directory /var/folders/4s/ccfp42j96qv43nl6fjlz7jzhl5jjtr/T/sbt_94b7dcac

**Comment by kolapkardhaval** [comment]
Is it trying to copy again and again? I see the file present already.

**Comment by eed3si9n** [comment]
Could you post the exact steps to reproduce your problems on our computers? It's hard to tell from just the error message what might be going on.

**Comment by kolapkardhaval** [comment]
I have a sample play project which gives BuildInfo when the uri /health/status is called. It gives back the response, however on the server side I see these errors.  The command I use to run the play service is: 
./activator ~run or sbt ~run

**Comment by loicdescotte** [comment]
Same issue here (with Play 2.7), when running the Play app with "sbt run" : 

[error] java.io.IOException: Bad address
[error]         at sun.nio.ch.FileDispatcherImpl.pwrite0(Native Method)
[error]         at sun.nio.ch.FileDispatcherImpl.pwrite(FileDispatcherImpl.java:66)
[error]         at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:89)
[error]         at sun.nio.ch.IOUtil.write(IOUtil.java:51)
[error]         at sun.nio.ch.FileChannelImpl.writeInternal(FileChannelImpl.java:772)
[error]         at sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:758)
[error]         at sun.nio.ch.FileChannelImpl.transferFromFileChannel(FileChannelImpl.java:633)
[error]         at sun.nio.ch.FileChannelImpl.transferFrom(FileChannelImpl.java:702)
[error]         at sbt.io.IO$.loop$1(IO.scala:835)
[error]         at sbt.io.IO$.$anonfun$copyFile$4(IO.scala:838)
[error]         at sbt.io.IO$.$anonfun$copyFile$4$adapted(IO.scala:829)
[error]         at sbt.io.Using.apply(Using.scala:22)
[error]         at sbt.io.IO$.$anonfun$copyFile$3(IO.scala:829)
[error]         at sbt.io.IO$.$anonfun$copyFile$3$adapted(IO.scala:828)
[error]         at sbt.io.Using.apply(Using.scala:22)
[error]         at sbt.io.IO$.copyFile(IO.scala:828)
[error]         at sbtbuildinfo.BuildInfo$BuildInfoTask.$anonfun$cachedCopyFile$1(BuildInfo.scala:100)
[error]         at sbtbuildinfo.BuildInfo$BuildInfoTask.$anonfun$cachedCopyFile$1$adapted(BuildInfo.scala:98)
[error]         at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:149)
[error]         at sbtbuildinfo.BuildInfo$BuildInfoTask.$anonfun$file$1(BuildInfo.scala:92)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:278)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] (Compile / buildInfo) java.io.IOException: Bad address
[error] java.lang.RuntimeException: Could not copy '/target/streams/compile/buildInfo/$global/streams/sbt-buildinfo/PMWBuildInfo.scala' to '/target/scala-2.12/src_managed/main/sbt-buildinfo/PMWBuildInfo.scala' (1073/1073 bytes copied)
[error]         at scala.sys.package$.error(package.scala:26)
[error]         at sbt.io.IO$.$anonfun$copyFile$4(IO.scala:841)
[error]         at sbt.io.IO$.$anonfun$copyFile$4$adapted(IO.scala:829)
[error]         at sbt.io.Using.apply(Using.scala:22)
[error]         at sbt.io.IO$.$anonfun$copyFile$3(IO.scala:829)
[error]         at sbt.io.IO$.$anonfun$copyFile$3$adapted(IO.scala:828)
[error]         at sbt.io.Using.apply(Using.scala:22)
[error]         at sbt.io.IO$.copyFile(IO.scala:828)
[error]         at sbtbuildinfo.BuildInfo$BuildInfoTask.$anonfun$cachedCopyFile$1(BuildInfo.scala:100)
[error]         at sbtbuildinfo.BuildInfo$BuildInfoTask.$anonfun$cachedCopyFile$1$adapted(BuildInfo.scala:98)
[error]         at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:149)
[error]         at sbtbuildinfo.BuildInfo$BuildInfoTask.$anonfun$file$1(BuildInfo.scala:92)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:278)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)

**Comment by gaeljw** [comment]
Same for me, did anyone find any workaround or fix for this?

**Comment by eed3si9n** [comment]
Does this still happen with sbt 1.3.13?

**Comment by gaeljw** [comment]
@eed3si9n I just checked on a project on which I had the issue, upgrading from sbt 1.2.8 to 1.3.13 fixed the issue.
I didn't check which sbt version actually fix the issue as the project was late behind but if latest does the job, it's great :)

Note for people coming here: we are using sbt-buildinfo 0.9.0.

**Comment by eed3si9n** [comment]
Thanks for the confirmation. I'm closing this for now.
