### ISSUE TITLE
 IO error while decoding /builds/api/my-project/sub-project/target/scala-2.12/src_managed/main/sbt-buildinfo/BuildInfo.scala with UTF-8

### ISSUE THREAD

**Issue by alexmnyc** [sbt/sbt-buildinfo#149]
Looks like there is an issue when a project is using sbt protobuf generators alongside sbt-buildinfo plugin

```
registry.proto: warning: Import google/protobuf/wrappers.proto but not used.
[info] Compiling protobuf
[info] Protoc target directory: /builds/api/my-project/sub-project/target/scala-2.12/src_managed/main
[info] Compiling 56 Scala sources to /builds/api/my-project/sub-project/target/scala-2.12/classes ...
[error] IO error while decoding /builds/api/my-project/sub-project/target/scala-2.12/src_managed/main/sbt-buildinfo/BuildInfo.scala with UTF-8: /builds/api/my-project/sub-project/target/scala-2.12/src_managed/main/sbt-buildinfo/BuildInfo.scala (No such file or directory)
[error] Please try specifying another one using the -encoding option
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
[error] Total time: 32 s, completed Jul 2, 2019 9:20:33 PM
```

**Comment by zabhi** [comment]
I am also facing the same issue. And again with protobuf compilation. I am using akka-grpc with this plugin.
@alexmnyc Can you share what you used?

**Comment by zabhi** [comment]
Digging more into it, I found that `compile` deletes the generated source file and replaces the main directory with generated protobuf sources. This should be happening because of ScalaPB / Akka-grpc

**Comment by zabhi** [comment]
Ha! Looks like I was not alone. https://github.com/thesamet/sbt-protoc/issues/6 has a workaround for this.

This is definitely not an issue with sbt-buildinfo. @eed3si9n feel free to close this. I think @alexmnyc's issue would be solved with the workaround in linked bug.

**Comment by zabhi** [comment]
Also related is https://github.com/sbt/sbt/issues/1583#issuecomment-262166588
