### ISSUE TITLE
Option to annotate values with their singleton types

### ISSUE THREAD

**Issue by kubukoz** [sbt/sbt-buildinfo#158]
Given that values in `BuildInfo` are constants, we should be able to expose their types as singleton types. That might allow some advanced type-level trickery for manipulating these values.

For example:

```scala
object BuildInfo {
  val name: "app" = "app"
}
```

Of course this only makes sense on Scala versions that support literal singleton types, so this would fail compilation on 2.12 and below, but the option would be opt-in so I don't think we need any special treatment for these Scala versions.

Something like this comes to mind:

```scala
buildInfoSingletonTypes := true
```

**Comment by eed3si9n** [comment]
I just implemented `final val` support here - https://github.com/sbt/sbt-buildinfo/pull/164
Would this cover your use case?

**Comment by kubukoz** [comment]
oh wow, how did I not notice this...

it does!!! Thank you.

![image](https://user-images.githubusercontent.com/894884/115802492-4b391a00-a3df-11eb-96d6-0c1c2cfbb557.png)
