### ISSUE TITLE
multiarg infix syntax looks like a tuple and will be deprecated

### ISSUE THREAD

**Issue by francisdb** [sbt/sbt-buildinfo#160]
Just saw this today on Scala `2.13.3` / buildinfo `0.8.0`

```
[warn] /.../BuildInfo.scala:20:95: multiarg infix syntax looks like a tuple and will be deprecated
[warn]     "name: %s, version: %s, scalaVersion: %s, sbtVersion: %s, gitHeadCommit: %s, buildOn: %s" format (
[warn]                                                                                               ^
```

**Comment by francisdb** [comment]
Never mind, already fixed in 80d0f04a092c481a4d9be9229ba821283bb99cee

**Comment by francisdb** [comment]
Hmm, seems that this has not yet been released

**Comment by eed3si9n** [comment]
I think this was part of 0.9.0 - https://github.com/sbt/sbt-buildinfo/releases/tag/v0.9.0

**Comment by francisdb** [comment]
I don't think so, the 9.0.0 tag points to a commit of 2018 and the fix commit was this year

**Comment by eed3si9n** [comment]
The fix commit https://github.com/sbt/sbt-buildinfo/pull/124/commits/88341ff80d5250c9c7197a5d2ab1267929fccb6d was in April 2018. https://github.com/sbt/sbt-buildinfo/commit/80d0f04a092c481a4d9be9229ba821283bb99cee fixes the README documentation :)
