### ISSUE TITLE
BuildInfo is not generated using sbt 1.3.13

### ISSUE THREAD

**Issue by rohit5ram** [sbt/sbt-buildinfo#166]
project/plugins.sbt

```
// The Play plugin
addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.8.0")
addSbtPlugin("com.eed3si9n" % "sbt-buildinfo" % "0.10.0")
```
build.sbt
```
lazy val root = (project in file(".")).enablePlugins(PlayScala)
  .enablePlugins(BuildInfoPlugin).settings(
    buildInfoKeys := Seq[BuildInfoKey](name, version, scalaVersion, sbtVersion),
    buildInfoPackage := "version"
  )
```

BuildInfo is never generated

**Comment by filipmacek** [comment]
Same here.

**Comment by Stivo** [comment]
It also didn't work in my project. I replaced it with following code in the build.sbt file:

```
lazy val generateBuildInfo = taskKey[Seq[File]]("Generates the build information")

generateBuildInfo := {
  val file = (resourceManaged in Compile).value / "buildinfo.properties"
  IO.write(file,
    s"""
       |version = ${version.value}
       |scalaVersion = ${scalaVersion.value}
       |sbtVersion = ${sbtVersion.value}
       |builtAt = ${new Date()}
       |builtAtMillis = ${System.currentTimeMillis()}
       |""".stripMargin)
  Seq(file)
}

resourceGenerators in Compile += generateBuildInfo
```

This will generate a buildinfo.properties file, which you can then read from the source code to get the desired values. I am sure it could be changed to generate the object directly, but this worked for me.

**Comment by gavares** [comment]
This seems to be the case with sbt 1.4.0 as well.

**Comment by filipmacek** [comment]
Also I noticed strange thing, src_managed directory wont be created if I build project using Intelij "Build project" button but If I compile project using "sbt compile" eveything is all right. Aren't they supposed to be the same ways of compiling the sbt project?

**Comment by SethTisue** [comment]
if still reproducible let us know
