### ISSUE TITLE
Please migrate from bintray for release

### ISSUE THREAD

**Issue by nicolasdalsass** [sbt/sbt-buildinfo#170]
Hi,

Since bintray is sunsetting its services pretty soon (https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/), it would be very nice if it were possible to publish this project elsewhere.

As of today, bintray is intermitently non accessible, making this plugin intermittently unavailable too.

Thanks a lot,
Nicolas

**Comment by tristankrass** [comment]
Any update?

**Comment by eed3si9n** [comment]
The existing versions were migrated - https://eed3si9n.com/bintray-to-jfrog-artifactory-migration-status-and-sbt-1.5.1

**Comment by nicolasdalsass** [comment]
Thanks a lot !
