### ISSUE TITLE
Generated import not compatible with new Scala 3 syntax

### ISSUE THREAD

**Issue by kubukoz** [sbt/sbt-buildinfo#171]
This makes it impossible to use the plugin under Scala 3 with `-source future`.

Example:

```scala
buildInfoKeys := Seq[BuildInfoKey](version),
buildInfoPackage := "com.kubukoz.next"
```

Generates:

```scala
// $COVERAGE-OFF$
package com.kubukoz.next

import scala.Predef._

/** This object was generated by sbt-buildinfo. */
case object BuildInfo {
  /** The value is "1.5.0+2-44650e3c-SNAPSHOT". */
  val version: String = "1.5.0+2-44650e3c-SNAPSHOT"
  override val toString: String = {
    "version: %s".format(
      version
    )
  }
}
// $COVERAGE-ON$

```

With error: 

```
`_` is no longer supported for a wildcard import; use `*` instead
This construct can be rewritten automatically under -rewrite -source future-migration.
```

Note that adding the `-rewrite -source future-migration` flags fixes it, but the code should probably be generated correctly in the first place.

**Comment by armanbilge** [comment]
I ran into this too. Here's my workaround:
```scala
// put this in project directory and use with:
// buildInfoRenderFactory := sbtbuildinfo.Scala3CaseObjectRenderer.apply

package sbtbuildinfo // couldn't access ScalaCaseObjectRenderer outside this pkg (?)

final case class Scala3CaseObjectRenderer(
    options: Seq[BuildInfoOption],
    pkg: String,
    obj: String)
    extends ScalaRenderer {
  private lazy val delegate = ScalaCaseObjectRenderer(options, pkg, obj)

  def extension: String = delegate.extension
  def fileType: BuildInfoType = delegate.fileType
  def renderKeys(infoKeysNameAndValues: Seq[BuildInfoResult]): Seq[String] =
    delegate.renderKeys(infoKeysNameAndValues).map {
      case "import scala.Predef._" => "import scala.Predef.*"
      case x => x
    }
}
```

**Comment by martingd** [comment]
@kubukoz and @eed3si9n, is that import of `scala.Predef._` even necessary at all?

Removing it, the code still compiles with Scala 3, 2.12, 2.11, and 2.10.
(I haven't tried to compile with earlier Scala versions as it requires a JDK earlier then 1.8.)

So I would suggest getting rid of the import altogether and also (which is a different issue) change code generation so all `val`s are final and without a type annotation as the `val`s then can be used as constants in annotation parameters.

For example, instead of generating

```scala
val version: String = "1.5.0+2-44650e3c-SNAPSHOT"
```

we should generate this

```scala
final val version = "1.5.0+2-44650e3c-SNAPSHOT"
```

**Comment by kubukoz** [comment]
About final vals - https://github.com/sbt/sbt-buildinfo/issues/158

As for the import, I also don't see why it'd be necessary unless someone disables the default imports.

**Comment by martingd** [comment]
@kubukoz 
> About final vals - #158

Thanks for the pointer. And it seems to do the trick also for annotation parameters.

> As for the import, I also don't see why it'd be necessary unless someone disables the default imports.

I had a discussion about this issue on Discord and it seems the import is there for exactly for that reason: if somene uses `Yno-imports` or `-Yno-predef`. See commit  e924a28

I am not sure why someone would do that and if we need to keep the import then the plugin will need to generate Scala 2/3 specific code.
