### ISSUE TITLE
BuildInfoOption.BuildTime causes empty scoverage reports

### ISSUE THREAD

**Issue by tarmath** [sbt/sbt-buildinfo#172]
Enabling BuildInfoOption.BuildTime causes empty coverage reports and a reported coverage of 100%

Steps to reproduce:

```shell
sbt new scala/scala-seed.g8
```

Create a `project/plugins.sbt`:
```scala
addSbtPlugin("com.eed3si9n" % "sbt-buildinfo" % "0.10.0")
addSbtPlugin("org.scoverage" % "sbt-scoverage" % "1.8.2")
```

Enable sbt-buildinfo on the project alongside these options:
```scala
buildInfoOptions += BuildInfoOption.BuildTime
buildInfoPackage := "build"
buildInfoKeys := Seq[BuildInfoKey](scalaVersion, sbtVersion)
```

Then just change the greeting lazy val in `src/main/scala/example/Hello.scala` into a def so it is accounted for by scoverage...

Finally, run test with coverage (more than once):
```shell
sbt coverage test coverageReport
```

The first time percentages are reported correctly, while subsequent runs will shows 100%/100% (and produce an empty report).

Deleting the target directory produces the right results again...

Note that if one were to remove the BuildTime option, reports would be generated perfectly each run.

**Comment by SethTisue** [comment]
cleaning up old tickets. if this is still reproducible in the current version, let us know and we can reopen it
