### ISSUE TITLE
Travis CI dropped

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt-buildinfo#177]
Given the poor handling of the recent security incident (https://arstechnica.com/information-technology/2021/09/travis-ci-flaw-exposed-secrets-for-thousands-of-open-source-projects/) I'm suspending Travis CI integration indefinitely.

Let's move on to GitHub Actions.

**Comment by mkurz** [comment]
@eed3si9n Can be closed.

**Comment by xuwei-k** [comment]
- https://github.com/sbt/sbt-buildinfo/pull/183
