### ISSUE TITLE
Scala 3 compatibility broken for ToJson

### ISSUE THREAD

**Issue by crispywalrus** [sbt/sbt-buildinfo#191]
BuildInfoOption.ToJson generates code that doesn't compile with scala 3.x. It uses `_` wildcards and tries to match against `scala.Int` (and many other types) These have been changed in scala 3 so perhaps we need a option or fork that produces scala 3 compatible code.

**Comment by arixmkii** [comment]
No need to fork. It could be added with `Scala3` renderers and then users could opt in to use this renderers, when they need Scala3 code. I never tried using generated sources for multiple Scala version, so, I don't know if it is possible to just generate for both Scala2 and Scala3 at the same time (w/o requiring additional support from SBT).

**Comment by rreckel** [comment]
Hi,

I just opened a pull request that should solve this issue.
Hope it helps

**Comment by SethTisue** [comment]
looks like this was fixed a while back by #198
