### ISSUE TITLE
Scala 2.13.x support

### ISSUE THREAD

**Issue by everson** [sbt/sbt-buildinfo#192]
Would this plugin be compatible with scala 2.13? Maybe it is just a case of cross releasing it?

**Comment by eed3si9n** [comment]
It's a code generator. The Scala version used to generate the code doesn’t have to match the Scala version used to compile the generated code.

**Comment by eed3si9n** [comment]
See https://github.com/sbt/sbt-buildinfo/blob/develop/src/sbt-test/sbt-buildinfo/multi/build.sbt

**Comment by everson** [comment]
Sorry, what I meant is that there is no binaries for scala 2.13 published for this plugin, so if you set your scala version used by sbt to be 2.13 (for consistency), it won’t find the plugin.

Sent from Proton Mail for iOS

29, eugene yokota ***@***.***> escreveu:
