### ISSUE TITLE
Not able to download version `0.10.0` from public infrastructure

### ISSUE THREAD

**Issue by tianx2** [sbt/sbt-buildinfo#194]
It seems like after this outage (https://www.scala-lang.org/blog/2023/04/20/sbt-plugins-community-repository.html), it seems like `sbt` expects packages to come from `Maven Central`. Unfortunately, it doesn't seem to be published there. **_Are there any plans to publish that version there along with any dependencies?_**

I tried to upgrade to version `0.11.0` but ran into issues downloading dependencies which I assume is running into similar issues.

**Comment by mkurz** [comment]
> I tried to upgrade to version `0.11.0` but ran into issues downloading dependencies which I assume is running into similar issues.

`0.11.0` is available (only) on Maven central, so there shouldn't be any problems using that version: https://repo1.maven.org/maven2/com/eed3si9n/sbt-buildinfo_2.12_1.0/0.11.0/
Which problems did you experience using 0.11.0?

**Comment by tianx2** [comment]
@mkurz I would get issues downloading other dependencies. I assume these are other plugins unrelated to `sbt-buildinfo` so I wanted to see if there is a way to specifically get `0.10.0`.

```
 	Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
00:00:55.874  [warn] 		org.foundweekends.giter8:sbt-giter8-scaffold:0.11.0-M4 (sbtVersion=1.0, scalaVersion=2.12)
00:00:55.874  [warn] 		com.twitter:scrooge-sbt-plugin:18.2.0 (scalaVersion=2.12, sbtVersion=1.0)
00:00:55.874  [warn] 		com.typesafe:sbt-mima-plugin:0.6.1 (sbtVersion=1.0, scalaVersion=2.12)
00:00:55.874  [warn] 		com.eed3si9n:sbt-assembly:0.14.6 (scalaVersion=2.12, sbtVersion=1.0)
00:00:55.874  [warn] 		com.dwijnand:sbt-compat:1.2.6 (scalaVersion=2.12, sbtVersion=1.0)
00:00:55.874  [warn] 
00:00:55.874  [warn] 	Note: Unresolved dependencies path:
00:00:55.874  [error] sbt.librarymanagement.ResolveException: Error downloading org.foundweekends.giter8:sbt-giter8-scaffold;sbtVersion=1.0;scalaVersion=2.12:0.11.0-M4
```

Should I just try to update these other plugins as well that have versions on Maven Central? Or should I try to get `0.10.0` for `sbt-buildinfo`? I am probably misstating that these are "dependencies" for `sbt-buildinfo` when they are just plugin dependencies for my specific project.

**Comment by eed3si9n** [comment]
I don't think the other errors are related to sbt-buildinfo.

**Comment by mkurz** [comment]
@tianx2 

> ```
> 00:00:55.874  [warn] 	Note: Unresolved dependencies path:
> 00:00:55.874  [error] sbt.librarymanagement.ResolveException: Error downloading org.foundweekends.giter8:sbt-giter8-scaffold;sbtVersion=1.0;scalaVersion=2.12:0.11.0-M4
> ```

You should upgrade to (one of) the latest release of Giter8:
* https://github.com/foundweekends/giter8/releases
* https://repo1.maven.org/maven2/org/foundweekends/giter8/sbt-giter8-scaffold_2.12_1.0/

**Comment by tianx2** [comment]
Thanks @mkurz.

I'm just going to answer my original question here which was where to download old versions of this `sbt` plugin after the general `sbt` outage. The new repository is located at https://scala.jfrog.io/artifactory/sbt-plugin-releases/ which is an `ivy` repository. Anybody looking for versions not migrated to `Maven Central` should look there. The `jfrog` repository information was posted in the `sbt` `1.5.1` release announcement (https://eed3si9n.com/bintray-to-jfrog-artifactory-migration-status-and-sbt-1.5.1). The announcement post will lead you to the general `jfrog artifactory` website, but you can find the specific repository information for `sbt-plugins` here - https://scala.jfrog.io/ui/repos/tree/General/sbt-plugin-releases. For my setup, I needed update my Sonatype Nexus proxy repository to point to the new location. After that, all my builds worked again.

For others willing to do the upgrade, you can find the latest version (`0.11.0`) on `Maven Central` (https://central.sonatype.com/).

**Comment by eed3si9n** [comment]
Please stop using scala.jfrog.io URL and use the redirect `https://repo.scala-sbt.org/scalasbt/` instead. We moved twice already, and for all likelihood we will move again, and it will be 404 again if you keep using the Bintray or Artifactory URLs directly.
