### ISSUE TITLE
0.11.0 missing from scala.jfrog.io

### ISSUE THREAD

**Issue by andrew-selvia** [sbt/sbt-buildinfo#197]
When I [search for sbt-buildinfo 0.11.0](https://scala.jfrog.io/ui/artifactSearchResults?name=sbt-buildinfo&type=artifacts) on [the JFrog Artifactory server](https://www.scala-sbt.org/1.x/docs/Bintray-For-Plugins.html), I do not see a listing. Corporate Artifactory servers thus do not know about 0.11.0. Should this be fixed?

**Comment by eed3si9n** [comment]
it's on Maven Central https://repo1.maven.org/maven2/com/eed3si9n/sbt-buildinfo_2.12_1.0/0.11.0/
