### ISSUE TITLE
infinite loop with Runtime keys

### ISSUE THREAD

**Issue by MasseGuillaume** [sbt/sbt-buildinfo#35]
for example:

```scala
buildInfoKeys := Seq[BuildInfoKey]((fullClasspath in Runtime))
```

**Comment by eed3si9n** [comment]
README says

> Tasks can be added only if they do not depend on sourceGenerators. Otherwise, it will cause an infinite loop.

To compute `fullClasspath in Runtime`, you need to generate all source code, including `BuildInfo.scala`. You should try something like `externalDependencyClasspath in Runtime`.
