### ISSUE TITLE
Request: Ability to specify location and name of `buildinfo.properties`

### ISSUE THREAD

**Issue by metasim** [sbt/sbt-buildinfo#36]
A bonus would be making the I/O operations separate tasks, enabling custom persistence mechanisms (e.g. database, or WebDAV, etc.). However, just allowing the location and name to be specified would provide a lot of flexibility for environment-specific customizations.

**Comment by eed3si9n** [comment]
If you want to just generate source code, sbt can do that without sbt-buildinfo.

**Comment by metasim** [comment]
Not interested in generating source code, just specifying the location and name of `buildinfo.properties` as used by sbt-buildinfo. Sorry if my original comment implied something else.
