### ISSUE TITLE
Race condition in multiple module project

### ISSUE THREAD

**Issue by nefilim** [sbt/sbt-buildinfo#37]
it appears to only happen when using multiple source generators (in my case, sbt-scalabuff & sbt-buildinfo), always need to run the compile step twice to succeed. the first pass fails with:

[error] source file 'sbtrace/child/target/scala-2.10/src_managed/main/sbt-buildinfo/BuildInfo.scala' could not be found

I've put together a small sample project to replicate the problem:

https://github.com/nefilim/sbtrace

**Comment by eed3si9n** [comment]
Please report this to sbt/sbt.
