### ISSUE TITLE
BuildInfo.toMap: Map[String, Any] triggers wartremover's Any wart 

### ISSUE THREAD

**Issue by dwijnand** [sbt/sbt-buildinfo#42]
By using `sbt-typelevel` I bring `sbt-buildinfo` into my build, but by also having `sbt-wartremover`, with its unsafe warts enabled (including the `Any` wart), wartremover flags `BuildInfo.toMap` for using `Any`.

**Comment by eed3si9n** [comment]
toMap is optional in 0.4.0.

**Comment by dwijnand** [comment]
Nice!
