### ISSUE TITLE
Support for setting multiple keys in BuildInfo.action style?

### ISSUE THREAD

**Issue by henricook** [sbt/sbt-buildinfo#43]
In this situation i want to set three BuildInfo keys from one sbt variable that contains them all - for this i have to run the regex three times, is it possible to set all the keys in one statement?

So in this case my 'flywayUrl' is jdbc:postgresql://myhost:myport/mydatabase?foo=bar

To match just the host i need to do this:

```scala
 BuildInfoKey.action("dbHost") { // Calculate the database host (extract from flywayUrl)
    val hostRegex = """jdbc:postgresql://(\w+):\d{2,5}/.+""".r
    flywayUrl.value match {
      case hostRegex(host) => host
    }
  }
```

Then i need to repeat this block twice more for the port and database, with different regexes

Any help appreciated, sorry if it's not really an "issue" - I couldn't find a freenode chatroom/suitable forum - please feel free to repoint me.

Edit: A regex matching all 3 parts i want would be: `val flywayUrlRegex = """jdbc:postgresql://([\w-]+):(\d{2,5})/([\w_-]+)?.+""".r`

**Comment by eed3si9n** [comment]
I'd say:
1. define a `def extractURL: (String, String, String)`
2. define custom setting keys that represents those values
3. include the keys into build info
