### ISSUE TITLE
Support generating simple Java class

### ISSUE THREAD

**Issue by analytically** [sbt/sbt-buildinfo#47]
It'd be great if there would be a way to generate a simple Java class containing the build information.

**Comment by npcode** [comment]
+1.

Or I want to know any Java-way to get the values from the Scala class generated by sbt-buildinfo.

**Comment by npcode** [comment]
Oops, It seems be already generating a Java class. I can get the values by Java code such as `hello.BuildInfo.version();`

**Comment by peter-fu** [comment]
@analytically Do you mean a Java source code or a compiled Java class?

Currently sbt-buildinfo (version 0.5.0 as the time writing) doesn't generate Java source code containing the build information. It generates Scala source code only, which will be compiled into some java class in the compile stage and can be used in all Java/Scala code.

As noted in https://github.com/sbt/sbt-buildinfo/blob/master/notes/0.5.0.markdown, it should be possible to generate Java source code, but I don't see use case for it yet. Would be great if you can provide some.

**Comment by axos88** [comment]
See PR: #98. All you need to do is write your own renderer.

**Comment by analytically** [comment]
It prevents sbt to be used for Java projects if it comes built-in :-).

**Comment by axos88** [comment]
Awesome. I don't think anybody prevents you from creating a PR with the renderer ;)

**Comment by arixmkii** [comment]
I created PR #167 which addresses this issue.

**Comment by SethTisue** [comment]
looks like this was fixed a while back by #167
