### ISSUE TITLE
Migrating from 0.3.2 to 0.4.0

### ISSUE THREAD

**Issue by kebeda** [sbt/sbt-buildinfo#50]
Issues encountered when switching from 0.3.2 to 0.4.0:

1. error: .enablePlugins(BuildInfoPlugin)  : not found: value BuildInfoPlugin

This is solved by changing the import statement from what it was in 0.3.2 ("import sbtbuildinfo.Plugin._") to just:

import sbtbuildinfo._

2. error: .settings(buildInfoSettings: _*).settings(  : not found: value buildInfoSettings

This one I'm stumped by, I can see it in your source file BuildInfoPlugin.scala line #38! I saw your migration notes, there you referred to a "commonSettings", which I couldn't see in your source. I tried changing buildInfoSettings to commonSettings, but got the same error.

I've got to be doing something silly, right?

**Comment by eed3si9n** [comment]
Auto plugin introduces `buildInfoSettings` automatically, so that's no longer needed. `commonSettings` is just a convention I use to define common settings across subprojects, and it's defined in the example code itself. If you don't have it, you don't have to add it.

**Comment by kebeda** [comment]
Problem is, I'm using a sourceGenerator to insert the date (among other
thigns) into buildInfoSettings:

            .settings(buildInfoSettings: _*).settings(
            sourceGenerators in Compile <+= buildInfo,
            buildInfoPackage := "com.package.name",
            buildInfoKeys ++= Seq[BuildInfoKey] (name, version,
scalaVersion, sbtVersion,
                "builtAt" -> {
                    val dtf = new java.text.SimpleDateFormat("yyyy-MM-dd
HH:mm:ss")
                    dtf.setTimeZone(java.util.TimeZone.getTimeZone("UTC"))
                    dtf.format(new java.util.Date())
                },
                "buildId" -> { Process("git rev-parse HEAD").lines.head },
                "buildMachine" -> { Process("hostname").lines.head }
            )
        )

How do I do this now in 0.4.0?

**Comment by eed3si9n** [comment]
Follow the migration guide:

1. `Remove settings(buildInfoSettings: _*).`.
2. Remove `sourceGenerators in Compile <+= buildInfo`,
3. Add `enablePlugins(BuildInfoPlugin).`

**Comment by kebeda** [comment]
Still no dice. No matter what variable I set, I get a "not found: value:
xxxx" error.

Did I mention I was doing this in a Play Framework application?

**Comment by eed3si9n** [comment]
Could you copy the exact error message with the whole build file on gist?

**Comment by kebeda** [comment]
@eed3si9n I finally bit the bullet and converted Build.scala to build.sbt, which resolved the problem. Although I suspect the solution @satybald gave in #51 may have worked as well, I feel better ditching the "legacy" Build.scala.

Thank you for sbt-buildinfo! Very nice work!

**Comment by eed3si9n** [comment]
I'm glad it worked out!
