### ISSUE TITLE
Add the location of generated BuildInfo.scala in README

### ISSUE THREAD

**Issue by freewind** [sbt/sbt-buildinfo#52]
It really spent me a lot of time to figure out why I can't find the generated `BuildInfo.scala`, until I asked a question on stackoverflow: 

http://stackoverflow.com/questions/29849942/i-used-sbt-buildinfo-in-my-project-but-it-doesnt-generate-the-buildinfo-scal

Can we add this location of generated BuildInfo.scala in README? It makes sense to the guys who are not very familiar with sbt.

**Comment by eed3si9n** [comment]
Please send a pull request on this.
