### ISSUE TITLE
Intellij or sbt-buildinfo issue ?

### ISSUE THREAD

**Issue by laguiz** [sbt/sbt-buildinfo#56]
To make intellij happy I have to add `target/classes_managed`. This help IDE to find the BuildInfo object.

I first thought it was an sbt/inetllij issue but I saw this thread : https://youtrack.jetbrains.com/issue/SCL-7182

I'm using default intellij sbt import.

Did I miss something? If not, do you have any idea how we could make this smoother (avoid change default project structure from sbt intellij)?

Versions used : 
- sbt-buildinfo version 0.4.0
- Playframework 2.3.9
- Intellij 14.1

Thanks.

**Comment by eed3si9n** [comment]
I haven't tested this but supposedly #75 might fix this issue. Please try sbt-buildinfo 0.6.0.
