### ISSUE TITLE
Consider auto-enabling sbt-buildinfo

### ISSUE THREAD

**Issue by mpilquist** [sbt/sbt-buildinfo#59]
Due to use of auto-plugins in 0.4.0, it is not currently possible to define a "parent plugin" -- akin to a Maven parent pom -- that enables and configures sbt-buildinfo *and* auto-enables for all JVM projects.

This came up when upgrading the scodec-build plugin to sbt-buildinfo 0.4.0. In the previous version (https://github.com/scodec/scodec-build/blob/ea96e7132bbf94f6cee52290a1fe7f53a4a3111b/src/main/scala/scodec/build/ScodecBuildSettings.scala), sbt-buildinfo was manually configured and enabled from `projectSettings`.

Note that adding `sbt-buildinfo` to `requirements` is not an option because then `ScodecBuildSettings` would only be enabled when `sbt-buildinfo` is manually enabled or alternatively `ScodecBuildSettings` is manually enabled. The goal is to keep `ScodecBuildSettings` auto-enabled for any JVM project while also auto-enabling `sbt-buildinfo`.

**Comment by mpilquist** [comment]
Duplicates #55

**Comment by sokrahta** [comment]
@eed3si9n might be worth looking at that pull request again
