### ISSUE TITLE
list elements in the Json-Object a not properly formatted

### ISSUE THREAD

**Issue by AlexanderRay** [sbt/sbt-buildinfo#62]
for example libraryDependencies should be an Json-Array

libraryDependencies: ["org.scala-lang:scala-library:2.11.6", "com.typesafe.play:twirl-api:1.1.1", "org.scala-lang:scala-compiler:2.11.6", ...]

now it is a string like that: "List(org.scala-lang:scala-library:2.11.6, com.typesafe.play:twirl-api:1.1.1, org.scala-lang:scala-compiler:2.11.6, ... )"

**Comment by remiguittaut** [comment]
This issue should be closed, it has been fixed in commit https://github.com/sbt/sbt-buildinfo/commit/cdb3fdb6287ae602fd72eedd4d5885ae5f351f93

**Comment by dwijnand** [comment]
Shipped in sbt-buildinfo 0.9.0.
