### ISSUE TITLE
Can't upgrade from 0.3.2 to 0.4.0

### ISSUE THREAD

**Issue by aloiscochard** [sbt/sbt-buildinfo#63]
After doing this change:

```
diff --git a/project/Common.scala b/project/Common.scala
index fa7dcfd..23c3ba7 100644
--- a/project/Common.scala
+++ b/project/Common.scala
@@ -3,7 +3,9 @@ import Keys._
 
 import sbtassembly._
 import sbtassembly.AssemblyKeys._
-import sbtbuildinfo.Plugin._
+import sbtbuildinfo._
+import sbtbuildinfo.BuildInfoPlugin._
+import sbtbuildinfo.BuildInfoKeys._
 
 import scala.collection.JavaConverters._
 import java.nio.file.{Paths, Files}
diff --git a/project/plugins.sbt b/project/plugins.sbt
index 398a2bd..57dd5d8 100644
--- a/project/plugins.sbt
+++ b/project/plugins.sbt
@@ -2,10 +2,10 @@ resolvers += "Typesafe repository" at "http://repo.typesafe.com/typesafe/release
 
 addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.3.7")
 
-addSbtPlugin("com.eed3si9n" % "sbt-buildinfo" % "0.3.2")
+addSbtPlugin("com.eed3si9n" % "sbt-buildinfo" % "0.4.0")
```

The plugin does not work anymore, SBT report the following error during compilation after `clean; compile;`:

```
[error] /home/alois/bestmile/platform/common/target/scala-2.11/src_managed/main/sbt-buildinfo/BuildInfo.scala:7: BuildInfo is already defined as case class BuildInfo
[error] case object BuildInfo {
```

Thanks

**Comment by godenji** [comment]
@aloiscochard looks like same issue opened a [couple of weeks ago](https://github.com/sbt/sbt-buildinfo/issues/60). Not that a reminder to @eed3si9n won't hurt, he's probably still jet lagged ;-)

**Comment by aloiscochard** [comment]
Hi @godenji, thanks for your quick answer.

Unfortunately I don't see how the linked issue could relate to that one, I mean the other one is about adding a missing tag to the git repository. Nothing about the code, right?

**Comment by godenji** [comment]
@aloiscochard yes, assumed there was a dep resolution problem in the linked issue (just getting started with this plugin now). After adding `addSbtPlugin("com.eed3si9n" % "sbt-buildinfo" % "0.4.0")` I see that everything resolves just fine.

In other words, ignore me ;-), I should be hitting your "real" issue soon enough...

**Comment by aloiscochard** [comment]
No worries @godenji :-)

Please keep us posted, I'm curios to know if I'm the only one to have issue with that version!

**Comment by eed3si9n** [comment]
Here's the migration guide - https://github.com/sbt/sbt-buildinfo/blob/master/Migration.md
I would need some repro project to work with. (Doesn't have to be minimalized)

**Comment by aloiscochard** [comment]
@eed3si9n thanks, I tried again by following the migration guide this time and it worked.
(from what I understand, I forgot to remove `settings(buildInfoSettings: _*)`)
Cheers
