### ISSUE TITLE
Cannot compile with IntelliJ

### ISSUE THREAD

**Issue by cosmincatalin** [sbt/sbt-buildinfo#69]
After installing the _sbt-buildinfo_ plugin, I cannot compile my project anymore in _IntelliJ_. The project compiles just fine using `sbt`.

The _IntelliJ_ error:

```
Error:scalac: Output path /Users/cosmin/dev/logs-processing/target/scala-2.10/classes is shared between: Module 'logs-processing' production, Module 'root' production
Output path /Users/cosmin/dev/logs-processing/target/scala-2.10/test-classes is shared between: Module 'logs-processing' tests, Module 'root' tests
Please configure separate output paths to proceed with the compilation.
TIP: you can use Project Artifacts to combine compiled classes if needed.
```

The configuration in `build.sbt` is as follows:

```
lazy val root = (project in file(".")).
    enablePlugins(BuildInfoPlugin).
    settings(
        buildInfoKeys := Seq[BuildInfoKey](name, version, scalaVersion, sbtVersion),
        buildInfoPackage := "eu.cosminsanda"
    )
```

Any tips on how to fix this annoying issue?

I should add that I now have an additional `root` module along my base project, which seems to cause the conflicting paths.

**Comment by mayacr86** [comment]
Same problem here. I'm using:

- Intellij 14
- sbt version 0.13.7
- scala version 2.11.6

**Comment by eed3si9n** [comment]
I haven't tested this but supposedly #75 might fix this issue. Please try sbt-buildinfo 0.6.0.
