### ISSUE TITLE
Missing maven artifacts in sonatype repository

### ISSUE THREAD

**Issue by wuschi** [sbt/sbt-buildinfo#71]
Hi,

where did the maven artifacts go to? i cannot find them on https://oss.sonatype.org/content/groups/public anymore.

Kind regards,
Thomas

**Comment by eed3si9n** [comment]
sbt-buildinfo is published to sbt community repo. http://repo.scala-sbt.org/

**Comment by wuschi** [comment]
Wow, that was fast. Thanks for the quick response.
