### ISSUE TITLE
Generated file's output folder.

### ISSUE THREAD

**Issue by evanbennett** [sbt/sbt-buildinfo#73]
Would some one be able to let me know why the generated file is output to a "sbt-buildinfo" folder:
https://github.com/sbt/sbt-buildinfo/blob/master/src/main/scala/sbtbuildinfo/BuildInfoPlugin.scala#L44
rather than something like:
sourceManaged.value / buildInfoPackage.value.replace(".", java.io.File.separator)

NOTE: I understand that sbt/Scala does not require the direct correlation between package and path that Java does, but I still find it a useful default.

Thanks.

**Comment by eed3si9n** [comment]
Namespacing: https://groups.google.com/forum/#!msg/sbt-dev/7gHACmFMgDg/_MBxSmvbAQAJ
