### ISSUE TITLE
Unusable with -Ywarn-unused-imports and -Xfatal-warnings under 2.12.0-M3

### ISSUE THREAD

**Issue by mpilquist** [sbt/sbt-buildinfo#74]
As of Scala 2.12.0-M3, the imports for `java.io.File` and `java.net.URL` are flagged as unused by scalac. As a result, sbt-buildinfo must either be removed or one of the scalac options must be removed.

**Comment by eed3si9n** [comment]
So we should change sbt-buildinfo to use fully qualified `java.io.File` etc or generate import only when it needs it.

**Comment by eed3si9n** [comment]
This is fixed in the latest - http://notes.implicit.ly/post/139340558764/sbt-buildinfo-060

**Comment by jedesah** [comment]
It's worth noting that the same things happens with scala `2.11.8+` , so I am very happy this has been fixed already! :+1:
