### ISSUE TITLE
Write file as utf8 instead of relying on defaultCharset

### ISSUE THREAD

**Issue by joprice** [sbt/sbt-buildinfo#76]
Since all Scala code can contain utf8 characters, IO.writeLines should be called with an explicit UTF-8 charset. I hit this problem with scalariform using 'rewriteArrowSymbols' (⇒), which produced a mangled BuildInfo file.

https://github.com/sbt/sbt-buildinfo/blob/d953034cad27ff88913572d7e30d4ae524a54e5b/src/main/scala/sbtbuildinfo/BuildInfo.scala#L65

**Comment by eed3si9n** [comment]
http://notes.implicit.ly/post/139340558764/sbt-buildinfo-060
