### ISSUE TITLE
Cannot use with -Yno-imports

### ISSUE THREAD

**Issue by jedesah** [sbt/sbt-buildinfo#80]
#78 breaks the use of `sbt-buildinfo` with the `-Yno-imports` compile flag.

Luckily the fix seems simple enough (hopefully it does not break yet another flag...), just fully qualify all the things.

**Comment by eed3si9n** [comment]
Did I break `String`?

**Comment by jedesah** [comment]
Well for us (and this might not be exhaustive to every project), `String`, `Boolean` and `format` on `String` cannot be found.

**Comment by jedesah** [comment]
Looks like `format` comes in through `StringLike`

**Comment by jedesah** [comment]
I can look into fixing it myself if you're busy. Wanted to post the issue first in order to do things "properly" and have the chance to discuss it. On the other hand, if you think it's a super quick fix and you already started looking at it, I won't duplicate effort.

**Comment by eed3si9n** [comment]
I'd be happy to take pull request. Here's an integration test where you can add this flag - https://github.com/sbt/sbt-buildinfo/blob/71d807e07ba79c4b210707d40f52b6250a7bf692/src/sbt-test/sbt-buildinfo/simple/build.sbt#L26

**Comment by jedesah** [comment]
Thx for the pointer! Will have a look at fixing after lunch. Hopefully we can get a new release out soon after the fix.

**Comment by eed3si9n** [comment]
Fixed by #81
