### ISSUE TITLE
Bug when compiling on scalaVersion upgrade

### ISSUE THREAD

**Issue by remy-figaro** [sbt/sbt-buildinfo#85]
Hi,

I have a problem when trying to upgrade my build.sbt scalaVersion from 2.10.6 to 2.11.6 using buildInfo plugin.
When I compile my project, I get this error :

> [error] /Users/jeanbombeur/Desktop/workspace/cvaden-hot-fca/target/src_managed/main/sbt-buildinfo/BuildInfo.scala:7: BuildInfo is already defined as case class BuildInfo
> [error] case object BuildInfo {
> [error]             ^
> [error] one error found
> [error](compile:compileIncremental) Compilation failed

The error seems weird since I just did a "clean" command and my "target" directory is clean.

Here is what my build.sbt looks like (I just obfuscated some names) :

<pre>import _root_.sbtassembly.Plugin.AssemblyKeys._
import _root_.sbtassembly.Plugin.MergeStrategy
import _root_.sbtassembly.Plugin.PathList
import _root_.sbtassembly.Plugin._
import _root_.sbtbuildinfo.BuildInfoPlugin
import _root_.sbtbuildinfo.BuildInfoPlugin.autoImport._
import _root_.sbtrelease.ReleasePlugin._
import com.typesafe.sbt.SbtNativePackager
import com.typesafe.sbt.SbtScalariform._
import com.typesafe.sbt.packager.SettingsHelper
import com.typesafe.sbt.packager.SettingsHelper
import com.typesafe.sbt.packager.universal.UniversalPlugin
import com.typesafe.sbt.packager.universal.UniversalPlugin.autoImport._
import sbtassembly.Plugin.AssemblyKeys._

name := """my-project"""

organization := "fr.me"

scalaVersion := "2.11.6"

scalacOptions ++= Seq("-deprecation", "-feature")

incOptions := incOptions.value.withNameHashing(true)

scalariformSettings
releaseSettings
assemblySettings

// Avro Section
sbtavrohugger.SbtAvrohugger.specificAvroSettings

mergeStrategy in assembly <<= (mergeStrategy in assembly) { (old) => {
  case m if m.toLowerCase.endsWith("manifest.mf") => MergeStrategy.discard
  case m if m.startsWith("META-INF") => MergeStrategy.discard
  case PathList("javax", "servlet", xs@_*) => MergeStrategy.first
  case PathList("org", "apache", xs@_*) => MergeStrategy.first
  case PathList("org", "jboss", xs@_*) => MergeStrategy.first
  case "about.html" => MergeStrategy.rename
  case "reference.conf" => MergeStrategy.concat
  case _ => MergeStrategy.first
}
}

artifact in(Compile, assembly) <<= (artifact in Compile, version) apply ((art, v) => {
  art
})

addArtifact(artifact in(Compile, assembly), assembly)

SettingsHelper.makeDeploymentSettings(Universal, packageBin in Universal, "zip")

resolvers += Resolver.sonatypeRepo("release")

resolvers ++= Common.resolvers

val sparkVersion = "1.5.2"
val kafkaVersion = "0.8.2.2"
val chillVersion = "0.8.0"
val slf4jVersion = "1.7.19"
val avroVersion = "1.8.0"
val elastic4sVersion = "1.7.5"

libraryDependencies ++= Seq(
  "org.apache.spark" %% "spark-streaming" % sparkVersion % "provided",
  "org.apache.spark" %% "spark-streaming-kafka" % sparkVersion,
  "org.apache.spark" %% "spark-sql" % sparkVersion % "provided" ,
  "org.apache.kafka" %% "kafka" % kafkaVersion % "provided",
  "org.apache.avro" % "avro" % avroVersion,
  "io.confluent" % "kafka-avro-serializer" % "1.0.1",
  "org.specs2" %% "specs2-core" % "3.7.2" % "test",
  "ch.qos.logback" % "logback-classic" % "1.1.3" % "provided",
  "org.slf4j" % "slf4j-api" % slf4jVersion % "provided",
  "com.twitter" %% "chill-avro" % chillVersion,
  "org.elasticsearch" %% "elasticsearch-spark" % "2.2.0" exclude("org.slf4j", "slf4j-api"),
  "com.maxmind.geoip2" % "geoip2" % "2.3.1",
  "com.sksamuel.elastic4s" %% "elastic4s-core" % elastic4sVersion,
  "eu.bitwalker" % "UserAgentUtils" % "1.19",
  "joda-time" % "joda-time" % "2.9.2",
  "com.github.ben-manes.caffeine" % "caffeine" % "2.2.2",
  "ua_parser" % "ua-parser" % "1.3.1.0"
)

dependencyOverrides ++= Set(
  "com.fasterxml.jackson.core" % "jackson-databind" % "2.4.4"
)

lazy val root = (project in file("."))
  .enablePlugins(SbtNativePackager, UniversalPlugin)
  .enablePlugins(BuildInfoPlugin).settings(
  // Build version parameters from Jenkins
  // @see https://wiki.jenkins-ci.org/display/JENKINS/Building+a+software+project#Buildingasoftwareproject-JenkinsSetEnvironmentVariables

  buildInfoKeys := Seq[BuildInfoKey](name, version in ThisBuild, scalaVersion, sbtVersion),

  buildInfoKeys ++= Seq[BuildInfoKey](
    "EXTRA_INFO" -> sys.env.getOrElse("EXTRA_INFO", "N/A"),
    "BUILD_NUMBER" -> sys.env.getOrElse("BUILD_NUMBER", "N/A"),
    "BUILD_ID" -> sys.env.getOrElse("BUILD_ID", "N/A"),
    "NODE_NAME" -> sys.env.getOrElse("NODE_NAME", "N/A"),
    "GIT_BRANCH" -> sys.env.getOrElse("GIT_BRANCH", "N/A"),
    "GIT_COMMIT" -> sys.env.getOrElse("GIT_COMMIT", "N/A"),
    "BUILD_AT" -> {
      val dtf = new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss")
      dtf.setTimeZone(java.util.TimeZone.getTimeZone("UTC"))
      dtf.format(new java.util.Date())
    })
)
</pre>

Since the bug presents itselft whereas the only change I made is the scalaVersion upgrade, I guess it must be somehow related.

This bug prevents me from compiling properly and I would really like to use the jenkins env variables.
Can you help me on this ?

Regards,

Rémy

**Comment by xuwei-k** [comment]
I think you should specify the `buildInfoPackage` or `buildInfoObject` key. should not use default values.


https://github.com/sbt/sbt-buildinfo/blob/v0.6.1/src/main/scala/sbtbuildinfo/BuildInfoKeys.scala
https://github.com/sbt/sbt-buildinfo/blob/v0.6.1/src/main/scala/sbtbuildinfo/BuildInfoPlugin.scala#L71-L72
