### ISSUE TITLE
Build fails with latest.release version

### ISSUE THREAD

**Issue by MojoJojo** [sbt/sbt-buildinfo#86]
Hi,

In my project, if I use `latest.release` as the version number instead of specifying a specific version e.g.

```
addSbtPlugin("com.eed3si9n" % "sbt-buildinfo" % "latest.release")
```

The build fails with the following error:

```
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.eed3si9n#sbt-buildinfo;latest.release: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
```

To debug, I downloaded the source for buildinfo and built it published it locally using `publishLocal`. If I then build by project, it succeeds. Perhaps the bintray version lacks a proper ivy.xml?

**Comment by eed3si9n** [comment]
Not sure if there's much we can do from sbt-buildinfo on this.
