### ISSUE TITLE
With both sbt-buildinfo and scrooge-sbt-plugin enabled, buildinfo fails

### ISSUE THREAD

**Issue by rtyley** [sbt/sbt-buildinfo#88]
We're using the [`scrooge-sbt-plugin`](
https://twitter.github.io/scrooge/SBTPlugin.html) to generate Scala classes from Thrift definitions, and it looks like that plugin and `sbt-buildinfo` have a bad interaction. With either of them disabled, things work, but with both enabled, a "X is already defined as case class X" error occurs (even if I change the name from the default 'BuildInfo').

Should be easily reproducible from this commit:

https://github.com/guardian/friendly-tailor/commit/aa85aad70d27f23c78715f9aea13a49d60a68383

```
> compile
[info] Compiling 6 Scala sources to /home/rtyley/development/friendly-tailor/target/scala-2.11/classes...
[error] /home/rtyley/development/friendly-tailor/target/scala-2.11/src_managed/main/sbt-buildinfo/Info.scala:6: Info is already defined as case class Info
[error] case object Info {
[error]             ^
[error] one error found
[error] (compile:compileIncremental) Compilation failed
[error] Total time: 2 s, completed 29-Apr-2016 13:45:48
```

**Comment by rtyley** [comment]
cc @travisbrown & @benjumanji, who've both worked on the scrooge-sbt-plugin.

**Comment by philwills** [comment]
I'm pretty certain this is a Scrooge, rather than an sbt-buildinfo issue, so have opened an issue there.

**Comment by eed3si9n** [comment]
I am guessing we are hitting this: sbt/sbt#1664 aka sbt/sbt-xjc#15.

**Comment by benjumanji** [comment]
As a "workaround that you can try at home" you can tweak `scroogeThriftOutputFolder` to be a subdir of `sourceManaged` rather than the whole folder. I am without internet at home and my current place of work doesn't use finagle / scrooge so I don't have a working setup that I could use to confirm that this works.
