### ISSUE TITLE
Problem with generated BuildInfo on Multibuild

### ISSUE THREAD

**Issue by grillorafael** [sbt/sbt-buildinfo#97]
Hi,

Sometimes when BuildInfo is generated, I get the write info but sometimes I get the project I `dependOn` info.

The context is a multi project build where:
`project2.dependsOn(project1)`

When running a `dist` on project2.

BuildInfo settings are setup as `commonSettings` with the following settings:

``` scala
buildInfoKeys := Seq[BuildInfoKey](name, version, scalaVersion, sbtVersion, libraryDependencies),
buildInfoPackage := CommonBuild.organization,
buildInfoOptions += BuildInfoOption.BuildTime,
buildInfoOptions += BuildInfoOption.ToMap,
buildInfoOptions += BuildInfoOption.ToJson
```

Sometimes I get project 1 buildInfo and sometimes I get project 2 buildinfo.

**Comment by dwijnand** [comment]
The problem by defining `buildInfoPackage := CommonBuild.organization` you're defining multiple versions of the same object.

For example if `CommonBuild.organization` is "org.example" you're creating two `BuildInfo` in package `org.example`, but with different values..

Put them in different packages, or give them different names.
