### ISSUE TITLE
Support for Scala 2.12

### ISSUE THREAD

**Issue by labra** [sbt/sbt-buildinfo#99]
Are there any plans to publish a version of sbt-buildinfo for scala 2.12?

**Comment by mslinn** [comment]
Does not generate any code for an SBT project that uses Scala 2.12 :(

**Comment by manub** [comment]
Version `0.6.1` works for me using Scala 2.12.1

**Comment by zella** [comment]
`0.7.0` works with scala 2.12.2

**Comment by francisdb** [comment]
this can be closed
